---

  - name: Ensure the Mono GPG key has been imported
    rpm_key:
      key: "{{ Radarr_mono_gpg_key }}"
      state: present

  - name: Ensure the Mono Yum repository is present
    copy:
      src: mono.repo
      dest: /etc/yum.repos.d/mono.repo
      owner: root
      group: root
      mode: 0644

  - name: Ensure the EPEL yum repository and key are present
    yum_repository:
      name: epel
      description: EPEL YUM repo
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  - name: Ensure mediainfo is installed
    dnf: name=mediainfo state=present enablerepo=PowerTools
  
  - name: Ensure mono locale extras is installed
    yum:
      name: mono-locale-extras
      state: present 
